package com.uconnect.backend.post.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.uconnect.backend.user.model.User;
import jdk.jfr.Timestamp;
import lombok.*;

import javax.validation.constraints.Null;
import java.util.Date;
import java.util.Set;

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Builder
@DynamoDBTable(tableName = "placeholder")
public class Comment {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Null(message = "New comment are assigned random IDs")
    private String id;

    @DynamoDBAttribute
    private User commentedBy;

    @DynamoDBAttribute
    @Timestamp
    private Date commentedAt;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "commentContent")
    private String commentContent;

    @DynamoDBAttribute
    private boolean anonymous;

    @DynamoDBAttribute
    private Set<User> commentLikes;

    @DynamoDBAttribute
    private Post parentPost;
}
