package com.uconnect.backend.post.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.uconnect.backend.user.model.User;
import lombok.*;

import javax.validation.constraints.Null;
import java.util.Date;
import java.util.List;
import java.util.Set;

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@Builder
@DynamoDBTable(tableName = "placeholder")
public class Post {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Null(message = "New posts are assigned random IDs")
    private String id;

    @DynamoDBAttribute
    private User postedBy;

    @DynamoDBAttribute
    private Date postedAt;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "postTitle")
    private String postTitle;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "postContent")
    private String postContent;

    @DynamoDBAttribute
    private boolean anonymous;

    @DynamoDBAttribute
    private Set<User> postLikes;

    @DynamoDBAttribute
    private List<Comment> postComments;
}
