version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
  post_build:
    commands:
      - echo Build completed successfully
      - echo Moving jar to project root
      - cp target/UConnectBackend.jar UConnectBackend.jar
artifacts:
  files:
    - UConnectBackend.jar
  discard-paths: no