server:
  port: 5000

db-setting:
  localdbport: N/A

db-table-name:
  user: "prod-userInfo"
  emailIndex: "emailIndex"
  emailVerification: "prod-emailVerification"
  eventBoardEventHidden: "prod-eventBoardEventHidden"
  eventBoardCommentHidden: "prod-eventBoardCommentHidden"
  eventBoardEventPublished: "prod-eventBoardEventPublished"
  eventBoardCommentPublished: "prod-eventBoardCommentPublished"
  eventBoardAuthorIndex: "authorIndex"
  eventBoardHostIndex: "hostIndex"
  eventBoardIndexIndex: "indexIndex"
  eventBoardTitleIndex: "titleIndex"
  eventBoardCommentParentIdIndex: "parentIdIndex"
  counter: "prod-counter"
  course: "prod-userCourse"

ses:
  sesFromAddress: team@uconnectbrown.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 529455990235-nthg83dnb7rrb2f7640h5cj06d4bfsqd.apps.googleusercontent.com
            client-secret: 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
            client-authentication-method: client_secret_post
            redirect-uri: https://www.uconnectbrown.com/auth/google/callback
