server:
  port: 5000

db-setting:
  localdbport: 8000

db-table-name:
  user: "dev-userInfo"
  emailIndex: 'emailIndex'
  emailVerification: "dev-emailVerification"
  eventBoardEventHidden: "dev-eventBoardEventHidden"
  eventBoardCommentHidden: "dev-eventBoardCommentHidden"
  eventBoardEventPublished: "dev-eventBoardEventPublished"
  eventBoardCommentPublished: "dev-eventBoardCommentPublished"
  eventBoardAuthorIndex: "authorIndex"
  eventBoardHostIndex: "hostIndex"
  eventBoardIndexIndex: "indexIndex"
  eventBoardTitleIndex: "titleIndex"
  eventBoardCommentParentIdIndex: "parentIdIndex"
  counter: "dev-counter"
  course: "dev-userCourse"
  classYearIndex: "classYearIndex"
  concentration: "dev-concentration"
  firstNameBucketIndex: "dev-firstNameBucketIndex"
  lastNameBucketIndex: "dev-lastNameBucketIndex"

ses:
  sesFromAddress: team@uconnectbrown.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 529455990235-nthg83dnb7rrb2f7640h5cj06d4bfsqd.apps.googleusercontent.com
            client-secret: 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
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:3000/auth/google/callback