server:
  port: 5000

db-setting:
  localdbport: 8000

db-table-name:
  user: FIX-ME
  emailIndex: 'emailIndex'
  emailVerification: "dev-emailVerification"
  eventBoardEventHidden: "dev-eventBoardEvent-hidden"
  eventBoardCommentHidden: "dev-eventBoardComment-hidden"
  eventBoardEventPublished: "dev-eventBoardEvent-hidden"
  eventBoardCommentPublished: "dev-eventBoardComment-published"
  eventBoardAuthorIndex: "authorIndex"
  eventBoardHostIndex: "hostIndex"
  eventBoardIndexIndex: "indexIndex"
  counter: "dev-counter"

ses:
  sesFromAddress: team@uconnectbrown.com

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 529455990235-nthg83dnb7rrb2f7640h5cj06d4bfsqd.apps.googleusercontent.com
            client-secret: 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
            client-authentication-method: client_secret_post
            redirect-uri: http://localhost:3000/auth/google/callback