server:
  port: 5000

db-setting:
  localdbport: 8000

db-table-name:
  user: FIX-ME
  emailIndex: 'emailIndex'

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 529455990235-nthg83dnb7rrb2f7640h5cj06d4bfsqd.apps.googleusercontent.com
            client-secret: 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
            client-authentication-method: client_secret_post
            redirect-uri: https://developers.google.com/oauthplayground