server:
  port: 5000

db-setting:
  localdbport: 8000

db-table-name:
  user: FIX-ME
  emailIndex: 'emailIndex'

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 43709566606-7aqrqos1en4nql7eifqcc5s1lhhgmp0c.apps.googleusercontent.com
            client-secret: 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
