package com.uconnect.backend.postingboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Null;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@Builder
@DynamoDBTable(tableName = "placeholder")
public class Comment {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Null(message = "New comments are assigned random IDs")
    @EqualsAndHashCode.Include
    private String id;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "parentIndex")
    @EqualsAndHashCode.Include
    private int parent;

    @DynamoDBAttribute
    @DynamoDBRangeKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexNames = {"authorIndex", "parentIndex"})
    private Date timestamp;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "authorIndex")
    private String author;

    @DynamoDBAttribute
    private String content;

    @DynamoDBAttribute
    private boolean isAnonymous;

    @DynamoDBAttribute
    private int likes;
}
