package com.uconnect.backend.postingboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBDocument;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import javax.validation.constraints.Null;
import javax.validation.constraints.Size;
import java.util.Date;

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@Builder
@DynamoDBDocument
public class Event {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Null(message = "New events are assigned random IDs")
    private String id;

    @DynamoDBAttribute
    @DynamoDBRangeKey
    @DynamoDBIndexRangeKey(globalSecondaryIndexNames = {"author", "host"})
    private Date timestamp;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "author")
    private String author;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "host")
    private String host;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "host")
    private Date startTime;

    @DynamoDBAttribute
    @Size(max = 1000, message = "Event description cannot be longer than 1000 characters")
    private String description;

    @DynamoDBAttribute
    private boolean isAnonymous;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "index")
    @EqualsAndHashCode.Include
    private long index;

    @DynamoDBAttribute
    private int likes;
}
