package com.uconnect.backend.postingboard.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.uconnect.backend.user.model.User;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.NoArgsConstructor;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Null;
import javax.validation.constraints.Size;
import java.util.Date;
import java.util.List;

@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(onlyExplicitlyIncluded = true)
@Builder
@DynamoDBTable(tableName = "placeholder")
public class Event {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    @Null(message = "New events are assigned random IDs")
    private String id;

    @DynamoDBAttribute
    private Date timestamp;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "titleIndex")
    @NotBlank(message = "New events must contain a title with at least one non-space character")
    @Size(max = 50, message = "Event title cannot exceed 50 characters")
    private String title;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "authorIndex")
    private String author;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "hostIndex")
    @Size(max = 100, message = "Event host cannot exceed 100 characters")
    private String host;

    @DynamoDBAttribute
    @NotNull(message = "New events must contain a start time")
    private Date startTime;

    @DynamoDBAttribute
    @Size(max = 1000, message = "Event description cannot exceed 1000 characters")
    private String description;

    @DynamoDBAttribute
    private boolean isAnonymous;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "indexIndex")
    @EqualsAndHashCode.Include
    // skip validation, set this to the correct value in controller/service
    private long index;

    @DynamoDBAttribute
    private ReactionCollection reactions;

    @DynamoDBAttribute
    @Size(max = 50, message = "Event location cannot exceed 50 characters")
    private String location;

    @DynamoDBIgnore
    private User authorInfo;

    @DynamoDBIgnore
    private List<Comment> comments;
}
